apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: three-tier
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk
  mysql-database: YXBwZGI=
  mysql-user: YXBwdXNlcg==
  mysql-password: YXBwcGFzc3dvcmQ=
